export const links = [
	{
		name: 'Home',
		hash: '#home',
	},
	{
		name: 'About',
		hash: '#about',
	},
	{
		name: 'Projects',
		hash: '#projects',
	},
	{
		name: 'Skills',
		hash: '#skills',
	},
	{
		name: 'Experience',
		hash: '#experience',
	},
	{
		name: 'Contact',
		hash: '#contact',
	},
	{
		name: 'CI/CD',
		hash: '/ci-cd',
	},
] as const


const skillsData = [
  "HTML",
  "CSS",
	"SCSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
	"middleware, ISR, SSG, SSR, route handlers, server actions",
  "Git",
  "TailwindCSS",
  "Prisma",
  "Redux",
  "GraphQL",
  "PostgreSQL",
  "Framer Motion",
  "React Hook Form",
  "Zod",
  "SQLite",
  "MongoDB",
  "Mongoose",
  "GSAP",
  "Directus",
  "Visx",
  "Vercel",
  "Docker",
  "Vite",
  "Figma",
  "Postgres",
  "Clerk",
  "AuthJS",
  "Next-intl",
  "Next Auth V5",
  "RadixUI",
  "Shadcn",
  "RTK",
  "RTK Query",
  "API Request Batching",
  "Rest API",
  "AWS (Lambda, S3, EC2)",
  "OVH",
  "CI/CD",
  "Cron tasks",
  "SEO",
  "robots.txt, sitemaps, meta tags, canonical, JSON-LD, ARIA",
  "FSD",
  "A/B testing",
  "Markdown editor",
  "Lodash",
  "p-list",
  "Puppeteer",
  "Lexical editor",
  "SST",
  "OpenNext",
  "reactbits",
];

// 🔹 Видаляємо дублі
export const uniqueSkills = [...new Set(skillsData)];

// 🔹 Об'єкт з кольорами для кожної технології
export const skillColors: Record<string, string> = {
  HTML: "#E34F26",
  CSS: "#1572B6",
	"SCSS": "#CC6699",
  JavaScript: "#F7DF1E",
  TypeScript: "#3178C6",
  React: "#61DAFB",
  "Next.js": "#4B5563",
	"middleware, ISR, SSG, SSR, route handlers, server actions": "#4B5563",
  Git: "#F05032",
  TailwindCSS: "#06B6D4",
  Prisma: "#2D3748",
  Redux: "#764ABC",
  GraphQL: "#E10098",
  PostgreSQL: "#336791",
  "Framer Motion": "#F20089",
  "React Hook Form": "#EC5990",
	RadixUI: "#0F172A",
  Zod: "#4B5563",
  SQLite: "#003B57",
  MongoDB: "#47A248",
  Mongoose: "#880000",
  GSAP: "#88CE02",
  Directus: "#4B5563",
  Visx: "#EDEDED",
  Vercel: "#4B5563",
  Docker: "#2496ED",
  Vite: "#646CFF",
  Figma: "#F24E1E",
  Postgres: "#336791",
  Clerk: "#5A67D8",
  AuthJS: "#0077CC",
  "Next-intl": "#4B5563",
  "Next Auth V5": "#4B5563",
  RTK: "#764ABC",
	Shadcn: "#4B5563",
  "RTK Query": "#764ABC",
  "API Request Batching": "#F59E0B",
  "Rest API": "#F59E0B",
  "AWS (Lambda, S3, EC2)": "#FF9900",
  OVH: "#123456",
  "CI/CD": "#2F855A",
  "Cron tasks": "#2F855A",
  "SEO": "#2B6CB0",
  "robots.txt, sitemaps, meta tags, canonical, JSON-LD, ARIA": "#2B6CB0",
  FSD: "#5A67D8",
  "A/B testing": "#F97316",
  "Markdown editor": "#F97316",
  Lodash: "#3490DC",
  "p-list": "#D97706",
  Puppeteer: "#2D3748",
  "Lexical editor": "#8B5CF6",
  SST: "#2563EB",
  OpenNext: "#000000",
  reactbits: "#10B981",
};